# Generated by Django 4.2.1 on 2023-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamirsinbaTrailers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('url', models.CharField(max_length=250)),
                ('preview', models.CharField(max_length=250)),
            ],
        ),
    ]
